api_version = "2025-01"

[[extensions]]
type = "ui_extension"
name = "fingrid-thankyou"
handle = "fingrid-thankyou"

[[extensions.targeting]]
target = "customer-account.order-status.customer-information.render-after"
module = "./src/index.jsx"