api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "fingrid-payment-method"
handle = "fingrid-payment-method"

[[extensions.targeting]]
target = "purchase.checkout.payment-method-list.render-after"
module = "./src/index.jsx"